"""Impact Predictor (Sprint 9.6) — estimates the metric impact of a patch
BEFORE it's applied, using the existing analyzers.

This is the predictive counterpart to the Patch Reviewer. Instead of
scoring after the fact, it estimates:

- Complexity change (cyclomatic complexity ↑ or ↓)
- Maintainability change (maintainability index ↑ or ↓)
- Line count change (+ / - / =)
- Documentation change (docstring coverage ↑ or ↓)

The predictions allow EDITH to surface confidence before the user applies
a patch, and to reject patches that clearly won't meet the improvement bar.
"""

from __future__ import annotations

import ast
from pathlib import Path
from typing import Optional

from app.core.config import logger
from app.autonomous.models import Patch

from app.review.metrics import FileMetrics, RepositoryMetrics
from app.review.analyzers.complexity import ComplexityAnalyzer
from app.review.analyzers.maintainability import MaintainabilityAnalyzer
from app.review.analyzers.readability import ReadabilityAnalyzer
from app.review.scoring import ScoringEngine


class ImpactPredictor:
    """Predicts the metric impact of a patch before it's applied.

    Uses the same analyzers as the Review Engine to compute estimated
    deltas for complexity, maintainability, readability, and documentation.
    The prediction is generated by running both old and new code through
    a fast, single-file version of the Review Engine.

    Usage::

        predictor = ImpactPredictor()
        predictor.predict(patches)
        for patch in patches:
            print(patch.predicted_complexity_delta)  # e.g. -5 means less complex
    """

    def __init__(self):
        self._complexity = ComplexityAnalyzer()
        self._maintainability = MaintainabilityAnalyzer()
        self._readability = ReadabilityAnalyzer()
        self._scoring = ScoringEngine()

    def predict(self, patches: list[Patch]) -> list[Patch]:
        """Estimate the impact of every patch.

        Populates:
            - ``patch.predicted_complexity_delta`` — estimated change in complexity
            - ``patch.predicted_maintainability_delta`` — estimated change in maintainability
            - ``patch.predicted_lines_added`` — estimated new code lines
            - ``patch.predicted_lines_removed`` — estimated removed lines
        """
        logger.info("ImpactPredictor: predicting impact for %d patches", len(patches))

        for patch in patches:
            try:
                self._predict_single(patch)
            except Exception as e:
                logger.warning(
                    "ImpactPredictor: failed to predict for %s: %s",
                    patch.file_path,
                    e,
                )
                patch.predicted_complexity_delta = 0.0
                patch.predicted_maintainability_delta = 0.0
                patch.predicted_lines_added = 0
                patch.predicted_lines_removed = 0

        return patches

    def _predict_single(self, patch: Patch) -> None:
        """Estimate the impact of a single patch."""
        # ── Analyze old code ────────────────────────────────────────
        before_metrics = self._analyze_code(patch.original_code)

        # ── Analyze new code ────────────────────────────────────────
        after_metrics = self._analyze_code(patch.new_code)

        # ── Compute predicted deltas ────────────────────────────────

        # Complexity: positive delta means more complex, negative is improvement
        avg_complexity_before = before_metrics.average_complexity if before_metrics.functions else 0
        avg_complexity_after = after_metrics.average_complexity if after_metrics.functions else 0
        complexity_delta = round(avg_complexity_after - avg_complexity_before, 1)

        # Maintainability: positive delta means more maintainable
        mi_before = before_metrics.maintainability_index if len(before_metrics.functions) > 0 else 50.0
        mi_after = after_metrics.maintainability_index if len(after_metrics.functions) > 0 else 50.0
        mi_delta = round(mi_after - mi_before, 1)

        # Lines: count added/removed code lines
        lines_before = before_metrics.code_lines
        lines_after = after_metrics.code_lines
        lines_added = max(0, lines_after - lines_before)
        lines_removed = max(0, lines_before - lines_after)

        # Docstring coverage
        doc_before = before_metrics.docstring_coverage
        doc_after = after_metrics.docstring_coverage

        # Score estimation (optional)
        # We can estimate the score delta here too

        patch.predicted_complexity_delta = complexity_delta
        patch.predicted_maintainability_delta = mi_delta
        patch.predicted_lines_added = lines_added
        patch.predicted_lines_removed = lines_removed

        logger.debug(
            "ImpactPredictor: %s → complexity=%+.1f maintainability=%+.1f lines=%+d",
            patch.file_path,
            complexity_delta,
            mi_delta,
            lines_added - lines_removed,
        )

    def _analyze_code(self, code: str) -> FileMetrics:
        """Run the full analysis pipeline on a code string and return FileMetrics.

        This runs ComplexityAnalyzer → MaintainabilityAnalyzer → ReadabilityAnalyzer
        in sequence, same as the Review Engine.
        """
        if not code.strip():
            return FileMetrics(path="_empty.py")

        file_path = Path("_predict.py")
        symbols = []

        fm = self._complexity.analyze_file(
            file_path=file_path,
            source=code,
            symbols=symbols,
        )
        fm = self._maintainability.analyze_file(
            file_path=file_path,
            source=code,
            symbols=symbols,
            file_metrics=fm,
        )
        fm = self._readability.analyze_file(
            file_path=file_path,
            source=code,
            symbols=symbols,
            file_metrics=fm,
        )
        return fm

    @staticmethod
    def confidence(patch: Patch) -> float:
        """Return a 0–1 confidence score for this prediction.

        Factors:
        - If the patch is small and targeted → higher confidence
        - If analyzers found comparable metrics → higher confidence
        - If the code is syntactically valid → higher confidence
        """
        if not patch.new_code.strip() or not patch.original_code.strip():
            return 0.0

        total_changes = patch.diff_lines_added + patch.diff_lines_removed
        if total_changes == 0:
            return 0.0

        # More changes = more uncertainty
        size_factor = max(0.3, min(1.0, 1.0 - (total_changes / 500)))

        # If we got both metrics, that's a good sign
        metrics_factor = 0.7
        if patch.predicted_complexity_delta != 0 or patch.predicted_maintainability_delta != 0:
            metrics_factor = 0.9

        return round(size_factor * metrics_factor, 2)
